AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Scrapy + Elasticsearch + CodePipeline + CodeDeploy
Parameters: 
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances.
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Type: String
    Description: EC2 instance type for Scrapy
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  AdminIP:
    Type: String
    Description: The IP address range that can be used to SSH to the EC2 instances.
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  S3BucketURL:
    Type: String
    Description: The bucket containing all nested stacks.
  GithubUser:
    Type: String
    Description: You Github account name.
  GithubRepo:
    Type: String
    Description: Repo name in your Github account.
  GithubOAuthToken:
    Type: String
    Description: Github OAuth token used to pull code and add hook.
    NoEcho: true
Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['', [!Ref S3BucketURL, '/', 'vpc.yml']] 
  Elasticsearch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['', [!Ref S3BucketURL, '/', 'elasticsearch.yml']] 
      Parameters:
        VpcId: !GetAtt Vpc.Outputs.VpcId
        SubnetId: !GetAtt Vpc.Outputs.PublicSubnet1
  Ec2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['', [!Ref S3BucketURL, '/', 'ec2.yml']]
      Parameters:
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType
        VpcId: !GetAtt Vpc.Outputs.VpcId
        PublicSubnetId: !GetAtt Vpc.Outputs.PublicSubnet1
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['', [!Ref S3BucketURL, '/', 'codepipeline.yml']]
      Parameters:
        GithubUser: !Ref GithubUser
        GithubRepo: !Ref GithubRepo
        GithubOAuthToken: !Ref GithubOAuthToken
