AWSTemplateFormatVersion: 2019-04-30
Description: >-
  Amazon EC2 service
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances.
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Type: String
    Description: EC2 instance type for Scrapy
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.
  VpcId:
    Type: String
    Description: VPC for EC2
  PublicSubnetId:
    Type: String
    Description: Public subnet ID for EC2
  AdminIP:
    Type: String
    Description: The IP address range that can be used to SSH to the EC2 instances.
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: prod-scrapy
      GroupDescription: >-
        Allow 22 for SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AdminIP
      VpcId: !Ref VpcId
  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess # change this
  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Ec2Role
  Ec2:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              ruby: []
          files:
            /home/ec2-user/install:
              source: !Join
                - ''
                - - https://aws-codedeploy-
                  - !Ref AWS::Region
                  - .s3.amazonaws.com/latest/install
              mode: '000755'
          commands:
            00-install-agent:
              command: ./install auto
              cwd: /home/ec2-user/
            01-cfn-signal:
              command: !Join
                - ''
                - - '/opt/aws/bin/cfn-signal -e 0 --stack '
                  - !Ref AWS::StackName
                  - ' --resource '
                  - ' Ec2 '
    Properties:
      KeyName: !Ref KeyName
      ImageId: ami-0de53d8956e8dcf80
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref Ec2SecurityGroup
      IamInstanceProfile: !Ref Ec2InstanceProfile
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: project
          Value: data-dash
        - Key: environment
          Value: production
      UserData: !Base64
        "Fn::Join":
          - ''
          - - "#!/bin/bash\n"
            - "yum -y update\n"
            - "yum -y install cfn-bootstrap\n"
            - "/opt/aws/bin/cfn-init -v "
            - " --stack "
            - !Ref AWS::StackName
            - " --resource Ec2"