AWSTemplateFormatVersion: 2019-04-30
Description: >-
  Amazon Elasticsearch service
Parameters:
  VpcId:
    Type: String
    Description: VPC for Elasticsearch security group
  SubnetId:
    Type: String
    Description: Subnet ID for Elasticsearch domain
Resources:
  ElasticsearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: prod-es
      GroupDescription: >-
        Allow 443 port 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchClusterConfig:
        InstanceCount: 1
        InstanceType: t2.small.elasticsearch
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      VPCOptions: 
        SecurityGroupIds:
          - !Ref ElasticsearchSecurityGroup
        SubnetIds:
          - !Ref SubnetId